version: "2"
services:
  gocdServer:
    container_name: "gocd-server01"
    build: "./gocd-server/"
    image: "ldelossa/gocd-server:16.12.0"
    ports: 
      - "8153:8153"
      - "8154:8154"
    
  gocdAgent:
    container_name: "gocd-agent01"
    build: "./gocd-agent/"
    image: "ldelossa/gocd-agent:16.12.0"
    environment: 
      - GO_SERVER_URL="https://gocd-server01:8154/go"
    depends_on:
      - "gocdServer"


